M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.04.1} date Thu 06 Apr 2023 09:49:15 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-06T21:49:15-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X81.7Y-123.3
X84.9Y-56.0
X140.3Y-123.3
T0
M30
