M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Sat 22 Jul 2023 03:19:08 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-22T15:19:08-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X81.7Y-123.3
X84.9Y-56.0
X140.3Y-123.3
T0
M30
